"""empty message

Revision ID: 38180a3ca867
Revises: None
Create Date: 2019-05-26 20:57:45.545000

"""

# revision identifiers, used by Alembic.
revision = '38180a3ca867'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userlogin', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_userlogin_lastname'), 'userlogin', ['lastname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userlogin_lastname'), table_name='userlogin')
    op.drop_column('userlogin', 'lastname')
    # ### end Alembic commands ###
